<?php
/**
 * Created by PhpStorm.
 * User: cyr
 * Date: 2019/2/21
 * Time: 16:48
 */

namespace backend\controllers;

use Yii;
use yii\web\Controller;
use backend\event\PlayEvent;
use ztaoyu\test\ztyGet;
use ztaoyu\test\request\request;
use cyr\junhuan\PayService;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;

class TestController extends Controller
{
    const EVENT_PLAY = 'play';

    public function init(){
        parent::init(); // TODO: Change the autogenerated stub
        //	绑定事件
        $this->on(self::EVENT_PLAY,['backend\extensions\Common','game']);
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['composer','test'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            $a =  '/'.ArrayHelper::getValue($action,'controller.module.requestedRoute','');
                            if (Yii::$app->user->can($a)) {
                                return true;
                            } else {
                                throw new \yii\web\HttpException('401','权限不足');
                            }
                        },
                    ],
                ],
            ],
        ];
    }

    public function actionTest(){
        $PlayEvent = new PlayEvent();
        $PlayEvent->gameName = '马里奥';
        $this->trigger(self::EVENT_PLAY,$PlayEvent);
    }

    public function actionComposer(){
        $micro = substr(microtime(), 2, 4);
        $order_no = 'TT' . date('YmdHis') . $micro;
        $pay_service = new PayService([
            'site_code' => Yii::$app->params['junhuan2']['sitecode'],
            'version' => '2.0.0',
            'device_type' => '2',
            'charset' => 'utf-8',
            'private_key_path' => Yii::$app->params['junhuan2']['privatekey'],
            'public_key_path' => Yii::$app->params['junhuan2']['publickey'],
        ]);
//        $pay_service->transTime = date('Y-m-d H:i:s', time());
//        $pay_service->appName = 'zongheng2plus1';
//        $pay_service->appVersion = '1.0.0';
//        $pay_service->notifyUrl = 'http://caradm.shangxiaban.cn/payment/notify/notify';
//        $pay_service->redirectUrl = 'http://caradm.shangxiaban.cn/payment/payment/redirect';
//        $pay_service->amount = '100';
//        $pay_service->orderNo = $order_no;
//        $pay_service->orderDate = date('Y-m-d H:i:s', time());
//        $pay_service->busCode = '3001';
//        $pay_service->quantity = '0';
//        $pay_service->remark1 = null;
//        $pay_service->remark2 = Yii::$app->request->getUserIP();
//        $pay_service->remark3 = null;
//        $pay_service->comm_para = '';
//        $pay_service->payerName = '李奕飞';
        $pay_service->xfksrq = date('Y-m-d H:i:s', time());
        $pay_service->openid = null;
        $pay_service->jszhm = '1.0.0';
        $pay_service->notifyUrl = 'http://caradm.shangxiaban.cn/payment/notify/notify';
        $pay_service->redirectUrl = 'http://caradm.shangxiaban.cn/payment/payment/redirect';
        $pay_service->jkbh = '0.01';
        $pay_service->orderNo = $order_no;

//        $fee_data = $pay_service->createFeeData();
//        $fee_data->sum = 100;
//
//        $fee_data->setNote1('123', '321', '2015', '20', '10', '11', '22', 'ff');
//
//        $pay_service->setFeeData($fee_data);
        $html = $pay_service->getPayorderHtml();

        print_r($html);
//        $PlayEvent = new request();
//        echo $PlayEvent->test();
    }
}