<?php
/**
 * Created by PhpStorm.
 * User: cyr
 * Date: 2019/2/18
 * Time: 13:16
 */

namespace frontend\controllers;

use Yii;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\UnauthorizedHttpException;
use yii\web\HttpException;

class XmlController extends Controller
{
    public function beforeAction($action)
    {
//        if(!Yii::$app->request->post('sign')){
//            throw new NotFoundHttpException();
//            return false;
//        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'hello' => 'mongosoft\soapserver\Action',
        ];
    }

    /**
     * @param string $name
     * @return string
     * @soap   #这里必须是包含'@soap'标签的doc注释块，否则生成的wsdl文件中将不会展示这个方法
     */
    public function getHello($name)
    {
        return 'Hello ' . $name;
    }

    /**
     * @param string $name
     * @return string
     * @soap   #这里必须是包含'@soap'标签的doc注释块，否则生成的wsdl文件中将不会展示这个方法
     */
    public function getGoodby($name)
    {
        return 'Goodby ' . $name;
    }
}