<?php
/**
 * Created by PhpStorm.
 * User: cyr
 * Date: 2019/6/20
 * Time: 10:48
 */

namespace common\modelsext;


class TableTitleRelation extends \common\models\TitleRelation
{
    public function behaviors()
    {
        return [
            [
                'class' => 'yii\behaviors\TimestampBehavior'
            ]
        ];
    }

    public function getMembertitles(){
        return $this->hasOne('\common\modelsext\TableMemberTitle',['id'=>'title_id'])->andOnCondition(['status' => 1]);
    }

    public function afterSave($insert, $changedAttributes)
    {
        if($insert){
            // 发送消息通知
            \Yii::$app->memberRemind->sendVerificationMessage($this->uid, [
                'title' => '称号变更',
                'content' => '恭喜您获得称号'.$this->membertitles->title
            ]);
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}